### ISSUE TITLE
Parent child relationship in ViewModel

### ISSUE THREAD

**Issue by pavanrajnit** [thebhaskara/brokenjs#1]
Can we have parent-child relationship in ViewModel objects.

**Comment by thebhaskara** [comment]
Thank you for your request pavanrajnit.
We have just added this functionality in Model (in commit 3083e3f62bfc04e2e2c0113cf487dfd97486f191)
Documentation can be found at https://thebhaskara.github.io/brokenjs/#Model-Relationship.
